---
date:  "`r format(Sys.time(), '%d %B, %Y')`"
always_allow_html: yes
output: 
  word_document:
    toc: true
    reference_docx: matrixbooking-report-reference.dotx

params:
  start_date: NULL
  end_date: NULL
  joined_observations: NULL
  bookings: NULL
  survey_name: NULL
  
title: "`r paste0('Meeting room usage report, ', params$survey_name)`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

#####

# Room bookings report for `r params$start_date` to `r params$end_date`

This report shows utilisation of meeting rooms in the working week, 9am-5pm Monday to Friday.


```{r summary, echo=FALSE, results='asis', dpi = 150, fig.width=8.9, fig.height=5}
joined_observations <- params$joined_observations

cat("## Summary table")

knitr::kable(permutation_summary(joined_observations), col.names = c("", "Working Hours", "proportions"))

cat("## Summary pie chart \n")

pie <- permutation_summary_pie(joined_observations)

pie
```

## Overall utilisation

```{r utilisation, echo=FALSE, results='asis', dpi = 150, fig.width=8.9, fig.height=5}
cat("\n\n## Usage by room type \n\n")
print(room_utilisation_permutation(joined_observations, "devicetype"))

cat("\n\n## Usage by weekday \n\n")
print(room_utilisation_permutation(joined_observations, "weekday"))

cat("\n\n## Occupancy heatmap \n\n")
time_of_day_heatmap(joined_observations, "sensor_value")

cat("\n\n## Bookings heatmap \n\n")
time_of_day_heatmap(joined_observations, "is_booked")
cat("\n\n")
time_of_day_bar(joined_observations)

```

## Charts by room

```{r charts_by_room, echo=FALSE, results='asis', dpi = 150, fig.width=8.9, fig.height=5}

room_list <- sort(unique(params$joined_observations$roomname))
for(room in room_list) {
  cat("\n\n## ", room, "\n\n", sep = "")
  filtered_observations <- joined_observations %>%
    dplyr::filter(roomname == room)
  
  print(occupancy_through_day(filtered_observations))
  
}
```